[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:8080 --workers 4 --timeout 120 backend.app:app"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
