name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Environment
        run: |
          echo "GitHub Workspace: $GITHUB_WORKSPACE"
          echo "Current Directory: $(pwd)"
          echo "Directory Contents: $(ls -la)"
          echo "Node Version: $(node -v)"
          echo "NPM Version: $(npm -v)"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Post-Checkout Debug
        run: |
          echo "Repository Contents:"
          ls -R
          echo "\nPackage.json Contents:"
          cat package.json
          echo "\nFrontend Package.json Contents:"
          cat frontend/package.json

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Node Setup Debug
        run: |
          echo "Node Version: $(node -v)"
          echo "NPM Version: $(npm -v)"
          echo "Global NPM Packages:"
          npm list -g --depth=0

      - name: Install Root Dependencies
        run: |
          echo "Installing root dependencies..."
          npm install
          echo "Root node_modules contents:"
          ls -la node_modules
          echo "Root package-lock.json contents:"
          cat package-lock.json

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: |
          echo "Current directory: $(pwd)"
          echo "Installing frontend dependencies..."
          npm install
          echo "Installing Vite explicitly..."
          npm install --save-dev vite@latest @vitejs/plugin-react@latest
          echo "Vite version:"
          npx vite --version
          echo "Installed packages:"
          npm list vite
          npm list @vitejs/plugin-react

      - name: Pre-Build Debug
        working-directory: frontend
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "\nVite config contents:"
          cat vite.config.js
          echo "\nIndex.html contents:"
          cat index.html

      - name: Build Frontend
        working-directory: frontend
        run: |
          echo "Starting build process..."
          echo "Vite config contents:"
          cat vite.config.js
          echo "\nStarting Vite build..."
          npx vite build --debug
          echo "\nBuild complete. Dist directory contents:"
          ls -la dist || echo "Dist directory not found!"
        env:
          VITE_API_URL: ${{ secrets.REACT_APP_API_URL }}
          NODE_ENV: production
          DEBUG: "vite:*"

      - name: Post-Build Debug
        working-directory: frontend
        run: |
          echo "Checking final build artifacts..."
          echo "Dist directory size: $(du -sh dist)"
          echo "JavaScript files in dist:"
          find dist -name "*.js" -type f -exec ls -lh {} \;
          echo "CSS files in dist:"
          find dist -name "*.css" -type f -exec ls -lh {} \;

      - name: Pre-Deploy Debug
        run: |
          echo "Final repository state:"
          git status
          echo "\nChecking frontend/dist path:"
          ls -la frontend/dist

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/dist
          branch: gh-pages
          clean: true

      - name: Post-Deploy Debug
        if: always()
        run: |
          echo "Deployment complete"
          echo "Final git status:"
          git status
          echo "\nBranches:"
          git branch -a
